# Generated by Django 4.2.17 on 2025-01-12 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test", "0002_remove_animal_log_id_remove_animals_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animal_log",
            name="date",
            field=models.DateTimeField(),
        ),
    ]
